services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: frontend
    ports:
      - "8001:80"
      - "4443:443"
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - transcendence
  postgres:
    image: postgres
    networks:
      - transcendence
    container_name: postgres
    environment:
      - POSTGRES_DB=trans
      - POSTGRES_USER=group
      - POSTGRES_PASSWORD=1234

    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql/data
volumes:
      data:
networks:
  transcendence:
    external: false
