services:
  nginx:
    image: owasp/modsecurity-crs:4.6.0-nginx-alpine-202409030409
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcendence

  gunicorn:
    build:
      context: .
      dockerfile: backend/gunicorn/Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    networks:
      - transcendence

networks:
  transcendence:
    driver: bridge
