services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: frontend
    ports:
      - "8001:80"
      - "4443:443"
    networks:
      - transcendence
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: backend
    ports:
      - "8000:8000"
    networks:
      - transcendence
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    networks:
      - transcendence
    container_name: postgres
    environment:
      - POSTGRES_DB=trans
      - POSTGRES_USER=group
      - POSTGRES_PASSWORD=1234
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U group -d trans'"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
      data:
networks:
  transcendence:
    external: false
