services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Containerfile
    container_name: frontend
    ports:
      - "8080:80"
      - "4443:443"
    networks:
      - transcendence
    depends_on:
      - backend
  backend:
    build:
      context: ./backend
      dockerfile: Containerfile
    container_name: backend
    env_file:
      - .env
    networks:
      - transcendence
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    networks:
      - transcendence
    container_name: postgres
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U group -d trans'"]
      interval: 5s
      timeout: 3s
      retries: 10
volumes:
      data:
networks:
  transcendence:
    external: false
