FROM debian:12

RUN apt-get update && apt-get upgrade -y && apt install -y \
    python3 \
    python3-pip \
    virtualenv \
    postgresql \
    postgresql-contrib \
    libpq-dev \
    python3-dev \
    python3-psycopg2

# RUN pip install psycopg2-binary

COPY requirements.txt .

RUN pip install --break-system-packages -r requirements.txt

COPY . .
COPY .. .

COPY entrypoint.sh /app/
RUN chmod +x /app/entrypoint.sh
ENTRYPOINT [ "/app/entrypoint.sh" ]

# ENTRYPOINT [ "python3" ]
# CMD [ "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]

EXPOSE 8000