FROM debian:12

RUN apt-get update && apt-get upgrade -y && apt install -y \
    python3 \
    python3-pip \
    virtualenv \
    postgresql \
    postgresql-contrib \
    libpq-dev \
    python3-dev \
    python3-psycopg2 

# RUN pip install psycopg2-binary

COPY requirements.txt .

RUN pip install --break-system-packages -r requirements.txt

# RUN apk add zlib-dev jpeg-dev gcc musl-dev  ca sert a pillow mais bug

COPY . .
COPY .. .

ENTRYPOINT [ "python3" ]
CMD [ "manage.py", "runserver", "0.0.0.0:8000", "--insecure"]

EXPOSE 8000
