# Generated by Django 3.1.6 on 2024-10-25 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0005_auto_20241025_1649'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('uid', models.CharField(max_length=50)),
                ('mail', models.CharField(max_length=50)),
                ('js_token', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('history', models.CharField(max_length=50)),
            ],
        ),
    ]
