# Generated by Django 3.1.6 on 2024-10-25 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentification', '0006_player'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Player',
        ),
    ]
