name: Test

on:
  pull_request:
    branches: [ "main" ]

jobs:
  test-container:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        env:
          - frontend
          - backend
    steps:
      - name: Checkout
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
      - name: Lint Containerfile
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        with:
          dockerfile: ./${{ matrix.env }}/Containerfile
      - name: Build the Docker image
        run: |
          cd ./${{ matrix.env }}/
          docker build . --file Containerfile
